### ISSUE TITLE
Is it possible to not generate the kotlin data class into an object ?

### ISSUE THREAD

**Issue by GeoffreyStemys** [apple/pkl-jvm-examples#1]
Hi everyone thank you for this amazing tool !

I am successfully using it with java 21 gradle 8.5 (with all default pkl gradle plugin values) and kotlin 1.9.21,
but I don't manage to generate exactly what I want:
If I have a `pkl` like:

```
module io.demo.birds

class Eagle {
  name: String
}
```

It will generate the following kotlin:

```kotlin
package io.demo

import kotlin.String

object Birds {
  data class Eagle(
    val name: String
  )
}
```

Is it possible to make him generate something without the `object` like:

```kotlin
package io.demo.birds

import kotlin.String
data class Eagle(
  val name: String
)
```

?

**Comment by GeoffreyStemys** [comment]
Apparently it's possible with something like:

```
module io.demo.birds.Eagle
name: String
```

I will have:
```kotlin
package io.demo.birds

import kotlin.String

data class Eagle(
  val name: String
)
```

Meaning that we cannot have multiple classes per file apparently.

**Comment by bioball** [comment]
Right; in Pkl, a module (a file) itself also a class (unless it `amends` some other module). And, classes declared within a module are like an inner static class.

For codegen purposes, we always turn one module into one Kotlin file.
